name: Build xatlas Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        #  - os: ubuntu-latest
        #    arch: x64
        #    cmake-arch: x64
        #  - os: ubuntu-latest
        #    arch: arm64
        #    cmake-arch: aarch64
          - os: windows-latest
            arch: x64
            cmake-arch: x64
          - os: windows-latest
            arch: arm64
            cmake-arch: ARM64
        #  - os: macos-latest
        #    arch: arm64
        #    cmake-arch: arm64

    steps:
      - name: Checkout xatlas
        uses: actions/checkout@v4
        with:
          repository: EvergineTeam/xatlas
          submodules: false

      - name: Configure xatlas (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -S . -B build -A ${{ matrix.cmake-arch }} -DCMAKE_BUILD_TYPE=Release

      - name: Build xatlas
        run: cmake --build build --config Release

      - name: Upload xatlas.dll (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: xatlas-${{ matrix.arch }}-dll
          path: build/**/*.dll

      - name: Upload libxatlas.so (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: xatlas-${{ matrix.arch }}-so
          path: build/**/*.so

      - name: Upload libxatlas.dylib (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: xatlas-${{ matrix.arch }}-dylib
          path: build/**/*.dylib
